# codemagic.yaml para o projeto lamafia

workflows:
  lamafia-android-build:
    name: Lamafia Android Build
    # Escolha a instância apropriada (ex: linux_x2 para builds Android mais rápidos)
    instance_type: linux_x2
    # Use a versão estável do Flutter ou especifique uma versão
    flutter: stable
    # Ambiente para build Android
    environment:
      android_signing:
        # Adicione suas credenciais de assinatura aqui (seguro via Codemagic UI)
        # keystore: Encrypted(...) 
        # keystore_password: Encrypted(...)
        # key_alias: Encrypted(...)
        # key_password: Encrypted(...)
      groups:
        - google_play_credentials # Grupo de variáveis para publicação no Google Play (opcional)

    scripts:
      - name: Set up local properties
        script: |
          echo "flutter.sdk=$FLUTTER_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      # Descomente e configure se você adicionou as credenciais de assinatura acima
      # - name: Set up keystore
      #   script: |
      #     echo $CM_KEYSTORE | base64 --decode > $CM_KEYSTORE_PATH
      #     echo "storeFile=$CM_KEYSTORE_PATH" > $CM_BUILD_DIR/android/key.properties
      #     echo "storePassword=$CM_KEYSTORE_PASSWORD" >> $CM_BUILD_DIR/android/key.properties
      #     echo "keyAlias=$CM_KEY_ALIAS" >> $CM_BUILD_DIR/android/key.properties
      #     echo "keyPassword=$CM_KEY_PASSWORD" >> $CM_BUILD_DIR/android/key.properties

      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Build Android APK
        script: |
          # Limpa builds anteriores (boa prática)
          flutter clean
          # Constrói o APK de release
          # Se você configurou a assinatura, o APK será assinado
          flutter build apk --release

    artifacts:
      # Define onde encontrar o APK gerado
      - build/app/outputs/flutter-apk/app-release.apk

    publishing:
      # Opcional: Configurar publicação automática para Google Play, email, Slack, etc.
      # email:
      #   recipients:
      #     - seu_email@exemplo.com
      #   notify:
      #     success: true
      #     failure: false # Notificar apenas em caso de sucesso
      # google_play:
      #   credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
      #   track: internal # Ou alpha, beta, production
      #   submit_as_draft: true

