# codemagic.yaml final para o projeto lamafia (Android APK)

workflows:
  lamafia-android-apk:
    name: Lamafia Android APK Build
    # Instância Linux é geralmente mais rápida e econômica para builds Android
    instance_type: linux_x2
    # Usar a versão estável do Flutter
    flutter: stable
    environment:
      # Grupo para credenciais de assinatura (configurar na UI do Codemagic)
      # android_signing:
      #   - keystore_credentials
      # Grupo para credenciais do Google Play (opcional, configurar na UI)
      # groups:
      #   - google_play_credentials
      vars:
        # Se precisar do google-services.json via variável (recomendado):
        # 1. Converta seu google-services.json para Base64
        # 2. Crie uma variável de ambiente na UI do Codemagic chamada GOOGLE_SERVICES_JSON
        # 3. Cole o conteúdo Base64 lá (marque como 'secure')
        # GOOGLE_SERVICES_JSON: Encrypted(...)
        # Se o google-services.json já está no repositório (menos seguro), ignore esta variável.

    scripts:
      - name: Set up local properties
        script: |
          echo "flutter.sdk=$FLUTTER_ROOT" > "$CM_BUILD_DIR/android/local.properties"

      # Descomente este bloco se você configurou a variável GOOGLE_SERVICES_JSON na UI
      # - name: Decode google-services.json
      #   script: |
      #     echo $GOOGLE_SERVICES_JSON | base64 --decode > $CM_BUILD_DIR/android/app/google-services.json
      #     echo "google-services.json created in android/app/"

      # Descomente e configure se você adicionou as credenciais de assinatura (keystore) na UI
      # - name: Set up keystore
      #   script: |
      #     echo $CM_KEYSTORE | base64 --decode > $CM_KEYSTORE_PATH
      #     echo "storeFile=$CM_KEYSTORE_PATH" > $CM_BUILD_DIR/android/key.properties
      #     echo "storePassword=$CM_KEYSTORE_PASSWORD" >> $CM_BUILD_DIR/android/key.properties
      #     echo "keyAlias=$CM_KEY_ALIAS" >> $CM_BUILD_DIR/android/key.properties
      #     echo "keyPassword=$CM_KEY_PASSWORD" >> $CM_BUILD_DIR/android/key.properties

      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Build Android APK
        script: |
          # Limpa builds anteriores (boa prática)
          flutter clean
          # Constrói o APK de release
          # Se você configurou a assinatura, o APK será assinado
          flutter build apk --release

    artifacts:
      # Define onde encontrar o APK gerado para disponibilizar no Codemagic
      - build/app/outputs/flutter-apk/app-release.apk

    publishing:
      # Opcional: Configurar notificação por email ou publicação
      # email:
      #   recipients:
      #     - seu_email@exemplo.com
      #   notify:
      #     success: true # Notificar apenas em caso de sucesso
      #     failure: false

