name: lamafia
description: 'Aplicativo LAMAFIA: Comunicação e organização para o clã.'
publish_to: 'none' # Prevent accidental publishing to pub.dev
version: 1.0.0+4 # Increment build number for apk

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6 # Specify a version for better stability

  # Firebase (Dependências essenciais)
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9

  # Estado e armazenamento
  provider: ^6.1.2
  shared_preferences: ^2.2.3

  # UI e formatação
  intl: ^0.19.0 # Necessário para formatação
  flutter_svg: ^2.0.10+1 # Para ícones SVG se forem usados

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1 # Para gerar ícones do app

flutter_icons:
  android: true
  ios: true
  # Ícone principal do app (foreground)
  image_path: "assets/images_png/1000216621.png"
  # Cor de fundo para ícones adaptativos Android
  adaptive_icon_background: "#000000"
  # Imagem foreground para ícones adaptativos Android (pode ser a mesma)
  adaptive_icon_foreground: "assets/images_png/1000216621.png"

flutter:
  uses-material-design: true

  assets:
    # Diretórios principais de assets
    - assets/images_png/
    - assets/audio/
    - assets/fonts/
    # Placeholders para assets futuros (adicionar arquivos quando disponíveis)
    - assets/images_svg/ # Para ícones vetoriais, se usados
    - assets/images_placeholders/ # Para logo oficial, splash, etc.

  fonts:
    - family: Gothic
      fonts:
        - asset: assets/fonts/gothic.ttf
    - family: Digital
      fonts:
        - asset: assets/fonts/digital.ttf
