name: lamafia
description: 'Aplicativo LAMAFIA: Comunicação e organização para o clã.'
publish_to: 'none' # Prevent accidental publishing to pub.dev
version: 1.0.0+5 # Increment build number after updates

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8 # Updated to latest stable

  # Firebase (Dependências essenciais atualizadas)
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6 # Adicionado para upload de imagens

  # Estado e armazenamento (Atualizado)
  provider: ^6.1.2 # Mantido, já é recente
  shared_preferences: ^2.5.3

  # UI e formatação (Atualizado)
  intl: ^0.20.2
  flutter_svg: ^2.0.10+1 # Mantido, já é recente

  # Funcionalidades Adicionadas (Atualizadas)
  image_picker: ^1.1.2
  agora_rtc_engine: ^6.3.2 # Atualizado para versão mais recente
  permission_handler: ^12.0.0+1 # Atualizado para versão mais recente

  # Dependências que estavam no pubspec.lock mas não no pubspec.yaml (adicionadas se necessário após pub get)
  # cached_network_image: ^3.4.1 # Exemplo, verificar se necessário
  # audioplayers: ^5.2.1 # Exemplo, verificar se necessário
  # connectivity_plus: ^5.0.2 # Exemplo, verificar se necessário
  # flutter_cache_manager: ^3.4.1 # Exemplo, verificar se necessário
  # flutter_local_notifications: ^17.2.4 # Exemplo, verificar se necessário
  # path_provider: ^2.1.5 # Exemplo, verificar se necessário

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0 # Updated to latest stable
  flutter_launcher_icons: ^0.14.3 # Updated to latest stable

flutter_icons:
  android: true
  ios: true
  # Ícone principal do app (foreground)
  image_path: "assets/images_png/1000216621.png"
  # Cor de fundo para ícones adaptativos Android
  adaptive_icon_background: "#000000"
  # Imagem foreground para ícones adaptativos Android (pode ser a mesma)
  adaptive_icon_foreground: "assets/images_png/1000216621.png"

flutter:
  uses-material-design: true

  assets:
    # Diretórios principais de assets
    - assets/images_png/
    - assets/audio/
    - assets/fonts/
    # Placeholders para assets futuros (adicionar arquivos quando disponíveis)
    - assets/images_svg/ # Para ícones vetoriais, se usados
    - assets/images_placeholders/ # Para logo oficial, splash, etc.

  fonts:
    - family: Gothic
      fonts:
        - asset: assets/fonts/gothic.ttf
    - family: Digital
      fonts:
        - asset: assets/fonts/digital.ttf

